# Generated by Django 4.0.5 on 2022-06-11 21:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_orderitem_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='supplier',
        ),
    ]
