# Generated by Django 4.0.4 on 2022-06-12 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_instruction_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='instruction',
            name='prog',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
