# Generated by Django 4.0.4 on 2022-06-12 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_remove_instruction_prog'),
    ]

    operations = [
        migrations.RenameField(
            model_name='brand',
            old_name='supplier',
            new_name='supplier_id',
        ),
    ]
