# Generated by Django 4.0.5 on 2022-06-13 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_alter_supplier_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='customer',
            new_name='customer_id',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='invoice_client',
            new_name='invoice_client_id',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='webshop',
            new_name='webshop_id',
        ),
    ]
