# Generated by Django 4.0.5 on 2022-06-14 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_alter_order_original_id_alter_order_webshop_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='order',
            new_name='order_id',
        ),
        migrations.RenameField(
            model_name='orderitem',
            old_name='product',
            new_name='product_id',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='brand',
            new_name='brand_id',
        ),
        migrations.RenameField(
            model_name='update',
            old_name='order',
            new_name='order_id',
        ),
        migrations.RenameField(
            model_name='update',
            old_name='status',
            new_name='status_id',
        ),
    ]
