# Generated by Django 4.0.5 on 2022-06-20 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_rename_order_orderitem_order_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='brand',
            old_name='supplier_id',
            new_name='supplier',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='customer_id',
            new_name='customer',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='invoice_client_id',
            new_name='invoice_client',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='webshop_id',
            new_name='webshop',
        ),
        migrations.RenameField(
            model_name='orderitem',
            old_name='order_id',
            new_name='order',
        ),
        migrations.RenameField(
            model_name='orderitem',
            old_name='product_id',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='brand_id',
            new_name='brand',
        ),
        migrations.RenameField(
            model_name='update',
            old_name='order_id',
            new_name='order',
        ),
        migrations.RenameField(
            model_name='update',
            old_name='status_id',
            new_name='status',
        ),
        migrations.RemoveField(
            model_name='order',
            name='original_id',
        ),
        migrations.AddField(
            model_name='order',
            name='original',
            field=models.CharField(default='1', max_length=15),
            preserve_default=False,
        ),
    ]
