# Generated by Django 4.0.4 on 2022-06-25 13:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0016_rename_item_orderitem_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='invoice_client',
        ),
        migrations.AddField(
            model_name='order',
            name='invoice',
            field=models.ForeignKey(default=16, on_delete=django.db.models.deletion.PROTECT, related_name='invoice', to='orders.customer'),
        ),
    ]
