# Generated by Django 4.0.4 on 2022-06-25 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0017_remove_order_invoice_client_order_invoice'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Instruction',
            new_name='Note',
        ),
    ]
