# Generated by Django 4.0.5 on 2022-06-29 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0023_remove_orderitem_product_orderitem_brand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='original',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
