# Generated by Django 4.0.5 on 2022-06-30 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0024_alter_order_original_delete_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='status',
            old_name='text',
            new_name='name',
        ),
    ]
