# Generated by Django 4.0.5 on 2022-07-05 11:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0026_alter_status_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='status',
            field=models.ForeignKey(default=16, on_delete=django.db.models.deletion.PROTECT, to='orders.status'),
            preserve_default=False,
        ),
    ]
