# Generated by Django 4.0.5 on 2022-07-06 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0027_orderitem_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='status',
            name='style_class',
            field=models.TextField(default='fw-normal'),
            preserve_default=False,
        ),
    ]
