# Generated by Django 4.0.5 on 2022-07-12 18:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0028_status_style_class'),
    ]

    operations = [
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='orders.status')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='orders.supplier')),
            ],
        ),
    ]
